security:
    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: admpass
                        roles: 'ROLE_API'
        hwi:
            id: "App\\Oauth\\Km77OauthUserProvider"

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            http_basic: ~
            pattern: ^/api
            anonymous: false

        secured_area:
            access_denied_url: /error403
            anonymous: true
            oauth:
                resource_owners:
                    km77: "/login/check-custom"
                login_path:        /connect/km77
                use_forward:       false
                failure_path:      /failure
                oauth_user_provider:
                    service: "App\\Oauth\\Km77OauthUserProvider"
            logout:
                path:   /logout
                target: /logoutfromaccounts

            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
        - { path: ^/connect/km77$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/api, roles: ROLE_API }
