#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /sonata

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /sonata
